adds requirements.txt to document dependencies
- these were partially pieced together by hand and partially filled in
  by pycharm's quick fix process.  this set is confimed working on my
  machine in the pycharm IDE and also by command line via build.bat
  generating an exe which runs successfully.  This is despite generating
  the following warnings:

      Error: Namespace packages not yet supported: Skipping package 'win32com.gen_py'

	14 missing Modules
	------------------
      ? PIL._imagingagg                     imported from PIL.ImageDraw
      ? PyQt4                               imported from PIL.ImageQt
      ? PyQt5                               imported from PIL.ImageQt
      ? _grabscreen                         imported from PIL.ImageGrab
      ? _imaging_gif                        imported from PIL.GifImagePlugin
      ? backports                           imported from setuptools.ssl_support
      ? packaging                           imported from pkg_resources
      ? setuptools_svn                      imported from setuptools.command.egg_info
      ? sha                                 imported from dns.entropy
      ? testing                             imported from cffi.recompiler
      ? urllib.pathname2url                 imported from setuptools.compat
      ? urllib.splittag                     imported from setuptools.compat
      ? urllib.url2pathname                 imported from setuptools.compat
      ? wincertstore                        imported from setuptools.ssl_support